### PR TITLE
Ready for GF

### PR DESCRIPTION
**Pull request by RosaWagner**
Hello
This is the build script and generated binaries. Since it is more intuitive to go from left to right with the sliders, I put the Text master as origin. Tell me if it is okay.

I noticed some accents are a bit misplaced, do you want to take care of it before I ship the fonts to Google, or it doesn't matter and I send them with no correction ?

- [ ] gravecomb in è + other letters)
- [ ] comma accent in rcommaaccent (and ss01)
- [ ] linebelow in rlinebelow
- [ ] circumflexcomb_hookabovecomb
- [ ] brevecomb_gravecomb
- [ ] periotcentered.locl.CAT supposed to be positioned like the dot in ldot

### CODE REVIEW

**Comment by Omnibus-Type** [comment]
Hi Rosa, many thanks for the support! 👍. Yes, you are indeed right about those details on diacritics, and we share the idea of placing the text axis as origin, but I don't know if in this case there is already a definition in the google fonts specs, just in case, check this specific topic with @m4rc1e. We will be waiting for any news.

**Comment by RosaWagner** [comment]
I don't understand, if you share the idea of placing the text (16pt) master as origin… what shall I check with Marc ?

**Comment by RosaWagner** [comment]
The default origin of a font with an optical size axis has not been yet defined in the spec (although it would make sens, I agree). We did chose the Text size as default in other project with an opsz axis (because it makes more sense) but of course it is flexible and if you think it is better to choose the display master, then we can, no problem.

**Comment by Omnibus-Type** [comment]
Rosa, I agree with the text master as origin, I said it in case it involves any complication with the specifications.

**Comment by RosaWagner** [comment]
Sorry, forgot to answer. It won't create complications, on the contrary ;) Just let me know if you want me to send the fonts after you merged or if you prefer to fix the diacritics detail first.

**Comment by Omnibus-Type** [comment]
Great Rosa, let's proceed the first way. Now I do the merge. Many thanks!

**Pull request merged**
